services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/build
      - static_volume:/build/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://iamramtin:myverygoodstrongpassword@db:5432/breezebound
    networks:
      - djangonetwork
  
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: "breezebound"
      POSTGRES_USER: "iamramtin"
      POSTGRES_PASSWORD: "myverygoodstrongpassword"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iamramtin -d breezebound"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - djangonetwork

networks:
    djangonetwork:
        driver: bridge
        
volumes:
  db_data:
  static_volume: